# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmdletoutputtype',
            name='output_type',
            field=models.CharField(db_index=True, max_length=480),
        ),
        migrations.AlterField(
            model_name='cmdletparameter',
            name='parameter_type',
            field=models.CharField(db_index=True, max_length=480),
        ),
    ]
