# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20171014_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmdlet',
            name='component',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cmdletoutputtype',
            name='output_type',
            field=models.CharField(db_index=True, max_length=1024, null=True),
        ),
    ]
